# Generated by Django 4.0 on 2025-01-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_address_customuser_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address1',
            field=models.CharField(max_length=40, verbose_name='都道府県 市区町村'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_code',
            field=models.CharField(max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(blank=True, max_length=5, verbose_name='番地'),
        ),
    ]
