# Generated by Django 4.0 on 2025-01-22 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_adrress2_alter_customuser_street_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='adrress2',
            new_name='address2',
        ),
    ]
