# Generated by Django 4.0 on 2024-11-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contract_status',
            field=models.CharField(default='未完了', max_length=10, verbose_name='仮契約ステータス'),
        ),
    ]
