# Generated by Django 4.0 on 2025-01-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_adrress2_customuser_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post_code',
            field=models.CharField(max_length=7, verbose_name='郵便番号'),
        ),
    ]
