# Generated by Django 4.0 on 2024-11-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0029_alter_pet_sex'),
        ('accounts', '0005_customuser_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contract_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contract_pets',
            field=models.ManyToManyField(blank=True, related_name='contracted_users', to='petapp.Pet', verbose_name='仮契約したペット'),
        ),
    ]
