# Generated by Django 4.0 on 2025-01-09 02:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('犬', '犬'), ('猫', '猫')], default='', max_length=10, verbose_name='種類')),
                ('size', models.CharField(choices=[('大型', '大型'), ('中型', '中型'), ('小型', '小型')], default='', max_length=10, verbose_name='サイズ')),
                ('color', models.CharField(default='', max_length=100, verbose_name='色')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='歳')),
                ('kinds', models.CharField(default='', max_length=100, verbose_name='種別')),
                ('disease', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='病気')),
                ('personality', models.CharField(default='', max_length=500, verbose_name='性格')),
                ('sex', models.CharField(choices=[('オス', 'オス'), ('メス', 'メス')], default='', max_length=10, verbose_name='性別')),
                ('phone_number', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$', '電話番号は半角数字のみで、10～15桁にしてください。')], verbose_name='電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('犬', '犬'), ('猫', '猫')], max_length=10)),
                ('size', models.CharField(choices=[('小型', '小型'), ('中型', '中型'), ('大型', '大型')], max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$', '電話番号は半角数字のみで、10～15桁にしてください。')], verbose_name='電話番号')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='petapp.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='petapp.pet')),
            ],
        ),
    ]
