# Generated by Django 4.0 on 2025-01-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('犬', '犬'), ('猫', '猫')], default='', max_length=20, verbose_name='種類'),
        ),
    ]
