# Generated by Django 4.0 on 2024-10-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_adopted',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='name',
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(),
        ),
    ]
