# Generated by Django 4.0 on 2024-10-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_remove_pet_breed_remove_pet_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('large', '大型'), ('medium', '中型'), ('small', '小型')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('dog', '犬'), ('cat', '猫')], default='unknown', max_length=10),
        ),
    ]
