# Generated by Django 4.0 on 2024-10-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_alter_pet_id_alter_pet_size_alter_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
