# Generated by Django 4.0 on 2025-01-15 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_alter_pet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='address_city',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='pet',
            name='address_detail',
            field=models.CharField(blank=True, default='Unknown', max_length=255, verbose_name='番地・建物名'),
        ),
        migrations.AddField(
            model_name='pet',
            name='address_prefecture',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='pet',
            name='postal_code',
            field=models.CharField(default='Unknown', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{4}$', '郵便番号はXXX-XXXXの形式で入力してください。')], verbose_name='郵便番号'),
        ),
    ]
