# Generated by Django 4.0 on 2025-01-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_pet_address_city_pet_address_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='address_detail',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='address_prefecture',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='postal_code',
        ),
    ]
