# Generated by Django 4.0 on 2024-10-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_alter_pet_id_alter_pet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=20)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('coat_color', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('large', '大型'), ('medium', '中型'), ('small', '小型')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('dog', '犬'), ('cat', '猫')], max_length=50),
        ),
    ]
