# Generated by Django 4.0 on 2024-10-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_surveyresult_alter_pet_color_alter_pet_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyResult',
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='survey_pets/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('large', '大型'), ('medium', '中型'), ('small', '小型')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('dog', '犬'), ('cat', '猫')], default='unknown', max_length=10),
        ),
    ]
