# Generated by Django 4.0 on 2025-01-16 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_pet_post_code_alter_pet_address_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$', '電話番号は半角数字のみで、10～15桁にしてください。')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='post_code',
            field=models.CharField(default='', max_length=7, verbose_name='郵便番号'),
        ),
    ]
