# Generated by Django 4.0 on 2025-01-16 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0011_alter_pet_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,11}$', '電話番号は半角数字のみで、10,11桁までにしてください。')], verbose_name='電話番号'),
        ),
    ]
