# Generated by Django 4.0 on 2025-01-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0012_alter_pet_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='location',
            field=models.CharField(default='', max_length=255, verbose_name='保護場所'),
        ),
    ]
