# Generated by Django 4.0 on 2024-11-06 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0012_alter_petimage_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='petapp.pet'),
        ),
    ]
