# Generated by Django 4.0 on 2025-01-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0013_pet_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='petimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
