# Generated by Django 4.0 on 2025-01-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0014_petimage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='経度'),
        ),
    ]
