# Generated by Django 4.0 on 2024-11-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0014_pet_disease_pet_personality_pet_sex_pet_syu_shelter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='shelter',
        ),
        migrations.DeleteModel(
            name='Shelter',
        ),
    ]
