# Generated by Django 4.0 on 2024-11-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0016_pet_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('大型', '大型'), ('中型', '中型'), ('小型', '小型')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('犬', '犬'), ('猫', '猫')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='pet_type',
            field=models.CharField(choices=[('犬', '犬'), ('猫', '猫')], max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='size',
            field=models.CharField(choices=[('小型', '小型'), ('中型', '中型'), ('大型', '大型')], max_length=10),
        ),
    ]
