# Generated by Django 4.0 on 2024-11-11 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0022_alter_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$', '電話番号は半角数字のみで、10～15桁にしてください。')]),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$', '電話番号は半角数字のみで、10～15桁にしてください。')]),
        ),
    ]
