# Generated by Django 4.0 on 2024-11-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0023_alter_pet_phone_number_alter_phonenumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/%Y/%m/%d/'),
        ),
    ]
