# Generated by Django 4.0 on 2024-11-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0024_alter_petimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
    ]
