# Generated by Django 4.0 on 2024-11-19 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0027_alter_pet_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='syu',
        ),
        migrations.AddField(
            model_name='pet',
            name='kinds',
            field=models.CharField(default='', max_length=100, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='歳'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(default='', max_length=100, verbose_name='色'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='disease',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='病気'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='personality',
            field=models.CharField(default='', max_length=500, verbose_name='性格'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$', '電話番号は半角数字のみで、10～15桁にしてください。')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('男の子', '男の子'), ('女の子', '女の子')], default='', max_length=10, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('大型', '大型'), ('中型', '中型'), ('小型', '小型')], default='', max_length=10, verbose_name='サイズ'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$', '電話番号は半角数字のみで、10～15桁にしてください。')], verbose_name='電話番号'),
        ),
    ]
