# Generated by Django 4.0 on 2024-11-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0028_remove_pet_syu_pet_kinds_alter_pet_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('オス', 'オス'), ('メス', 'メス')], default='', max_length=10, verbose_name='性別'),
        ),
    ]
