# Generated by Django 4.0 on 2024-10-21 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('messaging', '0002_pet_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelters', to='auth.user'),
        ),
    ]
