# Generated by Django 4.0 on 2024-10-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_pet_syu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='syu',
            field=models.CharField(max_length=100),
        ),
    ]
