# Generated by Django 4.0 on 2024-10-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_alter_pet_syu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('男の子', '男の子'), ('女の子', '女の子')], default='不明', max_length=10),
        ),
    ]
