# Generated by Django 4.0 on 2024-10-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_remove_pet_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PetImage',
        ),
    ]
