# Generated by Django 4.0 on 2024-10-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_rename_image_petimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='disease',
            field=models.CharField(default='健康', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='personality',
            field=models.CharField(default='健康', max_length=500),
        ),
    ]
