# Generated by Django 4.0 on 2024-10-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_pet_disease_pet_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='disease',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='inuneko',
            field=models.CharField(choices=[('犬', '犬'), ('猫', '猫')], default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='personality',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('男の子', '男の子'), ('女の子', '女の子')], default='NULL', max_length=10),
        ),
    ]
