# Generated by Django 4.0 on 2024-11-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_alter_pet_disease_alter_pet_inuneko_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='shelter',
        ),
        migrations.DeleteModel(
            name='Shelter',
        ),
    ]
