# Generated by Django 4.0 on 2024-11-07 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0016_pet_phone_number'),
        ('messaging', '0016_remove_pet_shelter_delete_shelter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petimage',
            name='pet',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='petapp.pet'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='petapp.pet'),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='PetImage',
        ),
    ]
