# Generated by Django 5.1.3 on 2024-11-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0017_remove_petimage_pet_alter_comment_pet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Karikeiyaku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("仮契約中", "仮契約中"),
                            ("キャンセル", "キャンセル"),
                            ("正式契約済", "正式契約済"),
                        ],
                        default="仮契約中",
                        max_length=50,
                        verbose_name="ステータス",
                    ),
                ),
            ],
        ),
    ]
