# Generated by Django 4.0 on 2024-11-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0018_alter_comment_user_alter_message_recipient_and_more'),
        ('messaging', '0019_alter_karikeiyaku_status'),
    ]

    operations = [
    ]
