# Generated by Django 5.1.3 on 2024-11-26 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0018_alter_comment_user_alter_message_recipient_and_more"),
        ("messaging", "0019_alter_karikeiyaku_status"),
    ]

    operations = []
