# Generated by Django 4.0 on 2024-11-27 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0021_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
