# Generated by Django 4.0 on 2024-11-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0029_alter_pet_sex'),
        ('accounts', '0004_alter_customuser_phone_number'),
        ('messaging', '0023_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='petapp.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_pets', to='accounts.customuser')),
            ],
            options={
                'unique_together': {('user', 'pet')},
            },
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
