# Generated by Django 5.1.3 on 2024-11-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0020_merge_20241126_0930"),
        ("messaging", "0023_favorite"),
    ]

    operations = []
