# Generated by Django 4.0 on 2024-11-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=20)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('living_environment', models.CharField(blank=True, max_length=255)),
                ('pet_personality', models.CharField(blank=True, max_length=255)),
                ('activity_level', models.CharField(blank=True, default='', max_length=255)),
                ('pet_size_preference', models.CharField(blank=True, max_length=255)),
                ('additional_requests', models.TextField(blank=True)),
            ],
        ),
    ]
