# Generated by Django 4.0 on 2024-11-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='living_environment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
