# Generated by Django 4.0 on 2024-11-15 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=20)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('living_environment', models.CharField(blank=True, max_length=255)),
                ('pet_personality', models.CharField(blank=True, max_length=255)),
                ('activity_level', models.CharField(blank=True, default='', max_length=255)),
                ('pet_size_preference', models.CharField(blank=True, max_length=255)),
                ('additional_requests', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('survey_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_histories', to='Survey.surveyresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_history', to='auth.user')),
            ],
        ),
    ]
