# Generated by Django 4.0 on 2024-11-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_surveyhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyhistory',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='additional_requests',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='age',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='living_environment',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_personality',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_size_preference',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='size',
        ),
    ]
