# Generated by Django 4.0 on 2024-11-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_remove_surveyhistory_activity_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresult',
            name='living_environment',
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='pet_age',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='pet_color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='pet_disease',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='pet_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='pet_image_urls',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='pet_personality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='pet_sex',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='pet_size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='pet_syu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='pet_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='activity_level',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='age',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='pet_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
