# Generated by Django 4.0 on 2024-11-19 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0027_alter_pet_age'),
        ('Survey', '0003_remove_surveyresult_living_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyhistory',
            name='matched_pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_survey_histories', to='petapp.pet'),
        ),
    ]
