# Generated by Django 4.0 on 2024-11-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0027_alter_pet_age'),
        ('Survey', '0004_surveyhistory_matched_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyhistory',
            name='matched_pet',
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='matched_pet',
            field=models.ManyToManyField(blank=True, to='petapp.Pet'),
        ),
    ]
