# Generated by Django 4.0 on 2024-11-18 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0025_alter_petimage_image'),
        ('Survey', '0004_remove_surveyresult_living_environment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_age',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_color',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_disease',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_id',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_image_urls',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_personality',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_sex',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_size',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_syu',
        ),
        migrations.RemoveField(
            model_name='surveyhistory',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='surveyhistory',
            name='matched_pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='survey_histories', to='petapp.pet'),
        ),
    ]
