# Generated by Django 4.0 on 2024-11-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_remove_surveyhistory_pet_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyHistory',
        ),
    ]
