# Generated by Django 4.0 on 2024-11-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0007_surveyresult_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='sex',
            field=models.CharField(choices=[('男の子', '男の子'), ('女の子', '女の子')], default='', max_length=10),
        ),
    ]
