# Generated by Django 4.0 on 2024-11-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0008_surveyresult_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='age_range',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
