# Generated by Django 4.0 on 2024-11-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0010_remove_surveyresult_age_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='disease',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='image_urls',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='sex',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
