# Generated by Django 4.0 on 2024-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0011_surveyresult_disease_surveyresult_image_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='age_range',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
