# Generated by Django 4.0 on 2024-11-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0013_remove_surveyresult_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='age_range',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
