# Generated by Django 4.0 on 2024-11-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0014_surveyresult_age_range'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyHistory',
        ),
    ]
