# Generated by Django 5.1.3 on 2024-11-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Survey", "0015_alter_surveyresult_disease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyresult",
            name="disease",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
