# Generated by Django 4.0 on 2024-11-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0015_alter_surveyresult_disease'),
        ('Survey', '0015_delete_surveyhistory'),
    ]

    operations = [
    ]
