# Generated by Django 4.0 on 2024-11-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0016_merge_20241121_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='disease',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
