<<<<<<< HEAD
# Generated by Django 4.0 on 2024-11-25 03:19
=======
# Generated by Django 4.0 on 2024-11-21 06:06
>>>>>>> 1f99a64563751b00960ff405a9a2c3b690a4988f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('Survey', '0016_merge'),
=======
        ('Survey', '0016_merge_20241121_1506'),
>>>>>>> 1f99a64563751b00960ff405a9a2c3b690a4988f
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='disease',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
