# Generated by Django 4.0 on 2024-11-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0016_merge_20241125_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='matched_pets',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='disease',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
