# Generated by Django 4.0 on 2024-11-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0016_merge'),
        ('Survey', '0016_merge_20241125_0937'),
    ]

    operations = [
    ]
