# Generated by Django 5.1.3 on 2024-11-25 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Survey", "0016_alter_surveyresult_disease"),
        ("Survey", "0017_alter_surveyresult_disease"),
    ]

    operations = []
