# Generated by Django 4.0 on 2024-11-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0017_surveyresult_matched_pets_alter_surveyresult_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresult',
            name='matched_pets',
        ),
    ]
