# Generated by Django 4.0 on 2024-11-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0028_remove_pet_syu_pet_kinds_alter_pet_age_and_more'),
        ('Survey', '0017_merge_0016_merge_0016_merge_20241125_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='disease',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='MatchingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('matched_pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_histories', to='petapp.pet')),
                ('survey_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_histories', to='Survey.surveyresult')),
            ],
        ),
    ]
