# Generated by Django 4.0 on 2024-11-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0018_alter_surveyresult_disease_matchinghistory'),
        ('Survey', '0018_merge_20241125_1104'),
    ]

    operations = [
    ]
