# Generated by Django 5.1.3 on 2024-11-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Survey", "0016_merge"),
        ("Survey", "0018_merge_20241125_1104"),
        ("Survey", "0018_remove_surveyresult_matched_pets"),
    ]

    operations = []
