# Generated by Django 4.0 on 2024-11-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0016_merge'),
        ('Survey', '0016_merge_20241121_1506'),
        ('Survey', '0018_remove_surveyresult_matched_pets'),
    ]

    operations = [
    ]
