# Generated by Django 4.0 on 2024-11-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0020_remove_matchinghistory_survey_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchingHistory',
        ),
    ]
