# Generated by Django 4.0 on 2024-11-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0022_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
