# Generated by Django 4.0 on 2025-01-09 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karikeiyaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='契約終了日')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('status', models.CharField(choices=[('仮契約中', '仮契約中'), ('キャンセル', 'キャンセル'), ('仮契約済', '仮契約済')], default='仮契約中', max_length=50, verbose_name='ステータス')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.pet', verbose_name='ペット')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー')),
            ],
        ),
    ]
