# Generated by Django 4.0 on 2025-01-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karikeiyaku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karikeiyaku',
            name='status',
            field=models.CharField(choices=[('仮契約中', '仮契約中'), ('キャンセル', 'キャンセル'), ('仮契約済', '仮契約済'), ('契約済み', '契約済み')], default='仮契約中', max_length=50, verbose_name='ステータス'),
        ),
    ]
