# Generated by Django 4.0 on 2025-01-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karikeiyaku', '0002_alter_karikeiyaku_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karikeiyaku',
            name='status',
            field=models.CharField(blank=True, choices=[('仮契約中', '仮契約中'), ('キャンセル', 'キャンセル'), ('仮契約済', '仮契約済'), ('契約済み', '契約済み')], default='仮契約中', max_length=50, null=True, verbose_name='ステータス'),
        ),
    ]
