# Generated by Django 4.0 on 2024-11-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karikeiyaku', '0003_alter_karikeiyaku_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karikeiyaku',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='作成日時'),
        ),
    ]
