# Generated by Django 4.0 on 2025-02-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karikeiyaku', '0003_alter_karikeiyaku_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karikeiyaku',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='契約終了日時'),
        ),
    ]
