# Generated by Django 4.0 on 2025-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karikeiyaku', '0009_alter_karikeiyaku_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='karikeiyaku',
            name='handover_date',
            field=models.DateField(blank=True, null=True, verbose_name='引き渡し日'),
        ),
        migrations.AlterField(
            model_name='karikeiyaku',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='契約開始日'),
        ),
    ]
