# Generated by Django 4.0 on 2025-02-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_phone_number'),
        ('karikeiyaku', '0010_karikeiyaku_handover_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karikeiyaku',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー'),
        ),
    ]
