# Generated by Django 4.0 on 2025-02-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_phone_number'),
        ('karikeiyaku', '0012_alter_karikeiyaku_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karikeiyaku',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー'),
        ),
    ]
